name: Full-stack tests

on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  acceptance_test_with_python_installation:
    name: Acceptance (logged-out-user/view-and-search-blog-posts)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository so that local actions can be used
        uses: actions/checkout@v4

      - name: Merge develop and set up dependencies
        uses: ./.github/actions/merge-develop-and-set-up-dependencies

      - name: Generate build files
        uses: ./.github/actions/generate-build-files

      - name: Generate modified suite name for artifacts
        id: generate_suite_name_for_artifacts
        # Replace slashes in the suite name with underscores for artifact naming.
        run: |
          SUITE_NAME="logged-out-user/view-and-search-blog-posts"
          echo "MODIFIED_SUITE_NAME=${SUITE_NAME//\//_}" >> $GITHUB_OUTPUT

      # 1st attempt, desktop
      - name: Run Desktop Acceptance Test
        run: >
          VIDEO_RECORDING_IS_ENABLED=0
          xvfb-run -a --server-args="-screen 0, 1285x1000x24"
          python -m scripts.run_acceptance_tests
          --skip-build
          --suite="logged-out-user/view-and-search-blog-posts"
          --prod_env

      # 2nd attempt, desktop (with recording)
      - name: Run Desktop Acceptance Test (Attempt 2 with screen recording)
        if: ${{ failure() }}
        run: >
          VIDEO_RECORDING_IS_ENABLED=1
          xvfb-run -a --server-args="-screen 0, 1285x1000x24"
          python -m scripts.run_acceptance_tests
          --skip-build
          --suite="logged-out-user/view-and-search-blog-posts"
          --prod_env

      - name: Upload Desktop Test Recordings as Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: desktop-acceptance-test-video-${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}
          path: /home/runner/work/oppia/oppia_full_stack_test_video_recordings/acceptance

      # 1st attempt, mobile
      - name: Run Mobile Acceptance Test
        run: >
          xvfb-run -a --server-args="-screen 0, 1285x1000x24"
          python -m scripts.run_acceptance_tests
          --skip-build
          --suite="logged-out-user/view-and-search-blog-posts"
          --prod_env
          --mobile

      # 2nd attempt, mobile (with recording)
      - name: Run Mobile Acceptance Test (Attempt 2 with screen recording)
        if: ${{ failure() }}
        run: >
          VIDEO_RECORDING_IS_ENABLED=1
          xvfb-run -a --server-args="-screen 0, 1285x1000x24"
          python -m scripts.run_acceptance_tests
          --skip-build
          --suite="logged-out-user/view-and-search-blog-posts"
          --prod_env
          --mobile

      - name: Upload Mobile Test Recordings as Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: mobile-acceptance-test-video-${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}
          path: /home/runner/work/oppia/oppia_full_stack_test_video_recordings/acceptance
